function PO = Dhv_plot(stage,P1,P2,P3);
%  Dhv_plot(stage,P1,P2,P3);
%
%  Kimtools for figures 1993-1995
%

% © Kim van Schagen, 1-Aug-95

if stage ==1,
  hmen = get(gcf,'currentmenu');
  holdyn = ishold;
  menstr = Transcod(get(hmen,'userdata'),1);

  fg = gcf;
  ag = gca;

  fx = get(fg,'units');
  set(fg,'units','pixels');
  pos = get(fg, 'position');
  set(fg,'units',fx);

  whostr = Dhv_getv;

  h_fig=figure('Menubar','none',...
          'NumberTitle','off',...
          'resize','off',...
          'Name','Plot command',...
          'keypress', ' ',...
          'visible','off');
  axes('visible','off','units','normalized','position',[0 0 1 1],...
       'xlim',[0 1],'ylim',[0 1]);

  h = Gch(2);
  width = 550;
  heigth = 10*h;
  left = pos(1)+.5*(pos(3)-width);
  bottom = pos(2)+.5*(pos(4)-heigth);

  pos = [left bottom width heigth];

  plotstr = str2mat('plot','surf','surfl','mesh');

  hcomm = uicontrol('units','normalized', ...
               'style','popup',...
               'position',[.05 .85 .10 .1],...
               'HorizontalAlignment','center',...
               'string',plotstr,...
               'value',1,...
               'callback','Dhv_setp(3);');

  text(0.2,0.9,'x-var:','verticalalignment','mid','fontsize',12,'horizontalal','left');

  h1 = uicontrol('units','normalized', ...
               'style','edit',...
               'position',[.3 .85 .65 .1],...
               'HorizontalAlignment','center');

  hh1 = uicontrol('units','normalized', ...
               'style','popup',...
               'string',menstr,...
               'position',[.3 .75 .325 .1],...
               'userdata',h1,...
               'HorizontalAlignment','center',...
               'Callback','Dhv_setp(2)');

  uicontrol('units','normalized', ...
               'style','popup',...
               'string',whostr,...
               'position',[.625 .75 .325 .1],...
               'userdata',h1,...
               'HorizontalAlignment','center',...
               'Callback','Dhv_setp(1)');

  text(0.2,0.65,'y-var:','verticalalignment','mid','fontsize',12,'horizontalal','left');

  h2 = uicontrol('units','normalized', ...
               'style','edit',...
               'position',[.3 .6 .65 .1],...
               'HorizontalAlignment','center');

  hh2 = uicontrol('units','normalized', ...
               'style','popup',...
               'string',menstr,...
               'position',[.3 .5 .325 .1],...
               'HorizontalAlignment','center',...
               'userdata',h2,...
               'Callback','Dhv_setp(2)');

  uicontrol('units','normalized', ...
               'style','popup',...
               'string',whostr,...
               'position',[.625 .5 .325 .1],...
               'HorizontalAlignment','center',...
               'userdata',h2,...
               'Callback','Dhv_setp(1)');

  ht3 = text(0.2,0.4,'z-var:','verticalalignment','mid',...
               'visible','off','fontsize',12,'horizontalal','left');

  h3 = uicontrol('units','normalized', ...
               'style','edit',...
               'position',[.3 .35 .65 .1],...
               'visible','off',...
               'HorizontalAlignment','center');

  hh3 = uicontrol('units','normalized', ...
               'style','popup',...
               'string',menstr,...
               'position',[.3 .25 .325 .1],...
               'HorizontalAlignment','center',...
               'userdata',h3,...
               'visible','off',...
               'Callback','Dhv_setp(2)');

  hp3 = uicontrol('units','normalized', ...
               'style','popup',...
               'string',whostr,...
               'position',[.625 .25 .325 .1],...
               'HorizontalAlignment','center',...
               'userdata',h3,...
               'visible','off',...
               'Callback','Dhv_setp(1)');

  hhold = uicontrol('units','normalized', ...
               'style','Checkbox',...
               'position',[.05 .6 .1 .1],...
               'HorizontalAlignment','center',...
               'string','Hold',...
               'value',holdyn);

  h_OK = uicontrol('Style','pushbutton',...
         'Units','normalized',...
         'position',[0.1 .05 .35 .1],...
         'HorizontalAlignment','center',...
         'String','OK', ...
         'Callback',...
     ['set(gcf,''visible'',''off'');figure(' int2str(fg)  ...
      ');eval([Dhv_plot(2,' int2str(h_fig) ...
      ') ''Dhv_plot(3,1,' num2str(h_fig) ...
      ');''],''Dhv_plot(3,0,' int2str(h_fig) ...
      '); '')']);

  h_Esc = uicontrol('Style','pushbutton',...
         'Units','normalized',...
         'position',[0.55 .05 .35 .1],...
         'HorizontalAlignment','center',...
         'String','Cancel',...
         'Callback','close');

  set(h_fig,'position',pos,'visible','on');
  set(h_fig,'userdata',[hmen hcomm h1 h2 h3 hhold hh3 hp3 ht3]);

elseif stage ==2, % vullen commando
  figui = P1;
  PlotM = str2mat('plot','surf','surfl','mesh');
  HoldM = str2mat('hold off;','hold on;');

  hs = get(figui,'userdata');
  strmen = get(hs(1),'userdata');
  val =get(hs(2),'value');
  plotcomm = Delspace(PlotM(val,:));
  str1 = Delspace(get(hs(3),'string'));
  str2 = Delspace(get(hs(4),'string'));
  if val == 1,
    set(hs(5),'string','');
  end
  str3 = Delspace(get(hs(5),'string'));

  holdstr = Delspace(HoldM(get(hs(6),'value')+1,:));

  % check variabelen en commando aantal)
  if (length(str1)+length(str2)+length(str3))==0,
    plotstr = '''Plotstrings are empty'';';
  else
    nr = (length(str1)>0)+ 2*(length(str2)>0) + 4*(length(str3)>0);
    strmat = str2mat(str1,str2,[str1 ',' str2],...
                     str3,[str1 ',' str3],[str2 ',' str3], ...
                     [str1 ',' str2 ',' str3 ]);

    plotstr = [holdstr plotcomm '(' Delspace(strmat(nr,:)) ');'];
  end;

  PO = plotstr;

elseif stage ==3,
  OK = P1;
  figui = P2;
  plotstr = Dhv_plot(2,figui);
  if plotstr(1) =='''',
    OK = 2;
  end;


  if OK==0,
    Textbox(str2mat('Plotcommand :',plotstr,'not correct',' ',...
             'Matlab error :',Transcod(lasterr)),'Error');
    figure(figui);
    set(figui,'visible','on')
  elseif OK == 2,
    Textbox(str2mat('Plotcommand not correct',' ',...
             'Error :', plotstr ), 'Error');
    figure(figui);
    set(figui,'visible','on')
  elseif OK == 1,
    % vullen menu
    hs = get(figui,'userdata');
    strmen = Transcod(get(hs(1),'userdata'),1);
    str1 = Delspace(get(hs(3),'string'));
    str2 = Delspace(get(hs(4),'string'));
    str3 = Delspace(get(hs(5),'string'));

    if strcmp(str1,str2)|strcmp(str3,str2),
      str2 = [];
    end;
    if strcmp(str1,str3),
      str3 = [];
    end;

    OK1 = 1;
    OK2 = 1;
    OK3 = 1;

    for tel = 1:size(strmen,1),
      menstr =  Delspace(strmen(tel,:));
      if length(str1) == length(menstr),
        if str1 == menstr,
          OK1 = 0;
        end;
      end;
      if length(str2) == length(menstr),
        if str2 == menstr,
          OK2 = 0;
        end;
      end;
      if length(str3) == length(menstr),
        if str3 == menstr,
          OK3 = 0;
        end;
      end;
    end;

    if OK3 & length(str3),
      if all(size(strmen)),
        strmen = str2mat(str3,strmen);
      else
        strmen = str3;
      end;
    end;

    if OK2 & length(str2),
      if all(size(strmen)),
        strmen = str2mat(str2,strmen);
      else
        strmen = str2;
      end;
    end;

    if OK1 & length(str1),
      if all(size(strmen)),
        strmen = str2mat(str1,strmen);
      else
        strmen = str1;
      end;
    end;

    if size(strmen,1)>10,
      strmen = strmen(1:10,:);
    end;

    if all(size(strmen)),
      set(hs(1),'userdata',Transcod(strmen,1));
    end;
    close(figui);
%    dhv_upda
  end;
end;


