function fig = verwrk_u()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load verwrk_u

h0 = figure('Units','points', ...
	'CloseRequestFcn','verwrk_f(''exit'')', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','Mdhv', ...
	'FileName','C:\DHV\stimela\STIMELA\STIMELA\Basis_Modules\Verdeelwerk\verwrk_u.m', ...
	'MenuBar','none', ...
	'Name','Input parameters distribution manifold', ...
	'NumberTitle','off', ...
	'PaperOrientation','landscape', ...
	'PaperPosition',[137.25 168 566.2499999999999 259.5], ...
	'PaperType','a4letter', ...
	'PaperUnits','points', ...
	'Position',[112.5 224.25 585 149.25], ...
	'Tag','Fig1', ...
	'ToolBar','none', ...
	'UserData',mat1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''new'') ', ...
	'CData',mat2, ...
	'ListboxTop',0, ...
	'Position',[0.75 131.25 17.25 18], ...
	'Tag','Pushbutton6', ...
	'TooltipString','New', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''load'') ', ...
	'CData',mat3, ...
	'ListboxTop',0, ...
	'Position',[19.5 131.25 17.25 18], ...
	'Tag','Pushbutton5', ...
	'TooltipString','Load', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''save'') ', ...
	'CData',mat4, ...
	'ListboxTop',0, ...
	'Position',[36.75 131.25 17.25 18], ...
	'Tag','Pushbutton4', ...
	'TooltipString','Save', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''saveas'') ', ...
	'CData',mat5, ...
	'ListboxTop',0, ...
	'Position',[54 131.25 17.25 18], ...
	'Tag','Pushbutton3', ...
	'TooltipString','Save As', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''exit'') ', ...
	'CData',mat6, ...
	'ListboxTop',0, ...
	'Position',[72.75 131.25 17.25 18], ...
	'Tag','Pushbutton2', ...
	'TooltipString','Exit');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' verwrk_f(''help'') ', ...
	'CData',mat7, ...
	'ListboxTop',0, ...
	'Position',[91.5 131.25 17.25 18], ...
	'Tag','Pushbutton1', ...
	'TooltipString','Help');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'Callback','verwrk_f(''Waarde1'');', ...
	'ListboxTop',0, ...
	'Position',[395.25 29.25 174 16.5], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','Edit1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[9.75 104.25 540 15.75], ...
	'String','BlokNaam: Basis_modules/Verdeelwerk|(aantal)', ...
	'Style','text', ...
	'Tag','BlokNaam');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[9 89.25 542.25 15.75], ...
	'String','FileNaam: verwrk_p.mat', ...
	'Style','text', ...
	'Tag','FileNaam');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[9.75 73.5 147 15.75], ...
	'String','Change value:', ...
	'Style','text', ...
	'Tag','txt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[10.5 30 376.5 15.75], ...
	'String','Number of outgoing streams :', ...
	'Style','text', ...
	'Tag','txt');
if nargout > 0, fig = h0; end
